name: ntds_2019_project
channels:
  - dglteam
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy=1.15.4
  - jsonschema=3.0.2
  - wheel=0.33.6
  - scipy=1.3.1
  - testpath=0.4.2
  - jupyterlab_server=1.0.6
  - pygments=2.4.2
  - ca-certificates
  - parso=0.5.1
  - pyrsistent=0.15.4
  - git=2.23.0
  - mkl=2019.4
  - dgl=0.3.1
  - send2trash=1.5.0
  - matplotlib-base=3.1.1
  - cycler=0.10.0
  - pandas=0.25.1
  - defusedxml=0.5.0
  - webencodings=0.5.1
  - bleach=3.1.0
  - pysocks=1.7.1
  - markupsafe=1.1.1
  - pytz=2019.2
  - openssl
  - six=1.12.0
  - pycparser=2.19
  - pandocfilters=1.4.2
  - sqlite=3.29.0
  - tornado=6.0.3
  - prometheus_client=0.7.1
  - nbconvert=5.6.0
  - jupyterlab=1.1.3
  - zeromq=4.3.2
  - pygsp=0.5.1
  - asn1crypto=1.2.0
  - networkx=2.3
  - entrypoints=0.3
  - setuptools=41.2.0
  - backcall=0.1.0
  - pytorch=1.2.0
  - jupyter_client=5.3.1
  - wcwidth=0.1.7
  - zlib=1.2.11
  - pyopenssl=19.0.0
  - scikit-learn=0.21.3
  - cffi=1.12.3
  - pandoc=2.7.3
  - prompt_toolkit=2.0.9
  - cryptography=2.7
  - json5=0.8.5
  - ipython_genutils=0.2.0
  - pip=19.2.3
  - traitlets=4.3.2
  - jedi=0.15.1
  - pyparsing=2.4.2
  - mistune=0.8.4
  - ipython=7.8.0
  - jinja2=2.10.1
  - nbformat=4.4.0
  - libsodium=1.0.17
  - kiwisolver=1.1.0
  - libpng=1.6.37
  - ninja=1.9.0
  - intel-openmp=2019.4
  - freetype=2.10.0
  - python=3.7.3
  - pickleshare=0.7.5
  - jupyter_core=4.4.0
  - libcblas=3.8.0
  - pyzmq=18.1.0
  - cpuonly=1.0
  - python-dateutil=2.8.0
  - idna=2.8
  - joblib=0.13.2
  - requests=2.22.0
  - libblas=3.8.0
  - ipykernel=5.1.2
  - notebook=6.0.1
  - chardet=3.0.4
  - liblapack=3.8.0
  - attrs=19.1.0
  - urllib3=1.25.6
  - decorator=4.4.0
  - terminado=0.8.2
  - python-louvain
  - nb_black
  - pyunlocbox